### ISSUE TITLE
Trying to update/modify resources that existed before Terraform was configured

### ISSUE THREAD

**Issue by hxvxt2** [hashicorp/terraform-provider-googleworkspace#110] opened 2021-07-11 13:25 UTC
Hi there,

I'm new to Terraform, I'm trying to figure out a way to update/modify resources (`googleworkspace_user`) that were created before Terraform was configured, but couldn't find any way to do that. And although I believe what I'm trying to do is either incorrect or not supported at this moment (give the provider was released recently, I decided to try it anyway.  Hoping I would get some insight by subsequent error messages. But I ended up with this rather generic error message that doesn't tell me what's going on. 
```
│ Error: Get "https://admin.googleapis.com/admin/directory/v1/users/meeseeks%40grozer.in?alt=json&prettyPrint=false": dial tcp: lookup admin.googleapis.com on 0.0.0.0:53: read udp 127.0.0.1:55005->127.0.0.1:53: read: connection refused
│
│   with data.googleworkspace_user.mee,
│   on gipl-offboard.tf line 28, in data "googleworkspace_user" "mee":
│   28: data "googleworkspace_user" "mee" {
│
╵
```

### Terraform Version
```
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/googleworkspace v0.2.0

Your version of Terraform is out of date! The latest version
is 1.0.2. You can update by downloading from https://www.terraform.io/downloads.html
```
### What I tried to do
- Tried to change the field `suspended` from `true` to `false` for a user

### Expected Behavior
User status should have been deactivated in Workplace

### Actual Behavior
```
│ Error: Get "https://admin.googleapis.com/admin/directory/v1/users/meeseeks%40grozer.in?alt=json&prettyPrint=false": dial tcp: lookup admin.googleapis.com on 0.0.0.0:53: read udp 127.0.0.1:55005->127.0.0.1:53: read: connection refused
│
│   with data.googleworkspace_user.mee,
│   on gipl-offboard.tf line 28, in data "googleworkspace_user" "mee":
│   28: data "googleworkspace_user" "mee" {
│
╵
```

**Comment by hxvxt2** [comment] 2021-07-11 13:36
I was introduced to `terraform import` by Google. I think it makes sense now.

**Comment by hxvxt2** [comment] 2021-07-11 15:31
Ok, so even if I import the resource `googleworkspace_user` I'll have to pass the `password` as a mandatory value. Is there a way to update a `googleworkspace_user` resource without having to pass the `password`? 

What am I missing?

Thanks
-v

**Comment by megan07** [comment] 2021-07-19 20:27
Closing this as a duplicate of https://github.com/hashicorp/terraform-provider-googleworkspace/issues/118

**Closed by megan07** 2021-07-19 20:27 UTC
Labels: bug
